# Generated by Django 5.2.1 on 2025-05-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id_forum', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ead.curso')),
            ],
            options={
                'db_table': 'forum',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id_postagem', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('autor_aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ead.aluno')),
                ('autor_professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ead.professor')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ead.forum')),
            ],
            options={
                'db_table': 'postagem',
            },
        ),
    ]
