# Generated by Django 5.2.1 on 2025-05-21 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='id_arquivo',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='aula_id_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ead.aula'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='descricao',
            field=models.CharField(default='Descrição não informada', max_length=255),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='url_arquivo',
            field=models.FileField(upload_to='arquivos/'),
        ),
        migrations.AlterModelTable(
            name='arquivo',
            table=None,
        ),
    ]
