# Generated by Django 5.2.1 on 2025-05-23 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('resposta_escolhida', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ead.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ead.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ead.questao')),
            ],
            options={
                'db_table': 'resposta_aluno',
            },
        ),
    ]
