# Generated by Django 5.2.1 on 2025-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(upload_to='imagens'),
        ),
    ]
