# Generated by Django 5.2.1 on 2025-05-31 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='modulo_id_modulo',
            field=models.ForeignKey(db_column='Modulo_ID_Modulo', on_delete=django.db.models.deletion.CASCADE, to='ead.modulo'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor_id_professor',
            field=models.ForeignKey(db_column='Professor_ID_Professor', on_delete=django.db.models.deletion.CASCADE, to='ead.professor'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='modulo_id_modulo',
            field=models.ForeignKey(db_column='Modulo_ID_Modulo', on_delete=django.db.models.deletion.CASCADE, to='ead.modulo'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='aula_id_aula',
            field=models.ForeignKey(db_column='Aula_ID_Aula', on_delete=django.db.models.deletion.CASCADE, to='ead.aula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_aluno',
            field=models.ForeignKey(db_column='ID_Aluno', on_delete=django.db.models.deletion.CASCADE, to='ead.aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id_curso',
            field=models.ForeignKey(db_column='ID_Curso', on_delete=django.db.models.deletion.CASCADE, to='ead.curso'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='curso_id_curso',
            field=models.ForeignKey(db_column='Curso_ID_Curso', on_delete=django.db.models.deletion.CASCADE, to='ead.curso'),
        ),
    ]
